### ISSUE TITLE
Few commits were added, however the VMs still didn't appear

### ISSUE THREAD

**Issue by PhashaD** [romankuchin/ica0002-2022#5]
I've added few commits, however the VM's didn't appear throughout the day.  http://193.40.156.67/students/PhashaD.html

**Comment by romankuchin** [comment]
TalTech cloud is broken today. ETA for the fix ~2h.

**Comment by MehmetSecgin** [comment]
Having this issue.
![image](https://user-images.githubusercontent.com/48296654/202453315-b18bbed7-bc92-42e8-bebd-32ce870077bf.png)
It says All is good but no machine is created. What could be the issue?
